;/*FB_PKG_DELIM*/

__d("GroupsCometEntityMenuChatIcon_thread.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[{kind:"RootArgument",name:"__relay_internal__pv__GroupsCometEntityMenuUseChatThumbnailsrelayprovider"}],kind:"Fragment",metadata:null,name:"GroupsCometEntityMenuChatIcon_thread",selections:[{condition:"__relay_internal__pv__GroupsCometEntityMenuUseChatThumbnailsrelayprovider",kind:"Condition",passingValue:!0,selections:[{alias:null,args:[{kind:"Literal",name:"height",value:40},{kind:"Literal",name:"width",value:40}],concreteType:"Image",kind:"LinkedField",name:"image",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"uri",storageKey:null}],storageKey:"image(height:40,width:40)"}]},{condition:"__relay_internal__pv__GroupsCometEntityMenuUseChatThumbnailsrelayprovider",kind:"Condition",passingValue:!1,selections:[{args:null,kind:"FragmentSpread",name:"useGroupsCometChatIcon_thread"}]}],type:"MessengerFBGroupChat",abstractKey:"__isMessengerFBGroupChat"};e.exports=a}),null);
__d("GroupsCometHeaderRecAffordanceControl_group$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"GroupsCometHeaderRecAffordanceControl_group$normalization",selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}]};e.exports=a}),null);
__d("GroupsCometHeaderRecAffordanceControl_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"GroupsCometHeaderRecAffordanceControl_group",selections:[{kind:"RequiredField",field:{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},action:"THROW",path:"id"},{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("GroupsCometEntityMenuChatIcon.react",["CometIcon.react","CometProfilePhoto.react","CometRelay","FundraiserFallbackImageUtils","GroupsCometEntityMenuChatIcon_thread.graphql","GroupsCometEntityMenuUseChatThumbnails.relayprovider","ImageIconSource","cr:3707","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=d("react"),j=(e=b("cr:3707"))!=null?e:function(a){return null};function a(a){var e=a.isSelected;a=a.thread;a=d("CometRelay").useFragment(h!==void 0?h:h=b("GroupsCometEntityMenuChatIcon_thread.graphql"),a);var f=j(a);a=a==null?void 0:(a=a.image)==null?void 0:a.uri;if(c("GroupsCometEntityMenuUseChatThumbnails.relayprovider").get()){return i.jsx(c("CometProfilePhoto.react"),{shape:"circle",size:48,source:{uri:(a=a)!=null?a:d("FundraiserFallbackImageUtils").FALLBACK_ICON_URI}})}return i.jsx(c("CometIcon.react"),{color:e?"highlight":void 0,icon:(a=f)!=null?a:new(c("ImageIconSource"))(d("FundraiserFallbackImageUtils").FALLBACK_ICON_URI,20,20),size:20})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("EntityMenuTabEnum",["$InternalEnum"],(function(a,b,c,d,e,f){"use strict";a=b("$InternalEnum")({USER:"user",ADMIN:"admin"});c=a;f["default"]=c}),66);
__d("GroupsCometHeaderRecAffordanceControl.react",["fbt","ix","CometRelay","GroupsCometHeaderRecAffordanceControl_group.graphql","TetraButton.react","fbicon","promiseDone","react","requireDeferred","usePreviousSurfaceForGroupLogging","useRouteProductAttribution"],(function(a,b,c,d,e,f,g,h,i){"use strict";var j,k=d("react"),l=d("react").useRef,m=c("requireDeferred")("GroupClickActionFalcoEvent").__setRef("GroupsCometHeaderRecAffordanceControl.react");function a(a){var e=a.group,f=a.isExpanded,g=a.onPress,n=d("CometRelay").useFragment(j!==void 0?j:j=b("GroupsCometHeaderRecAffordanceControl_group.graphql"),e),o=c("useRouteProductAttribution")();a=c("usePreviousSurfaceForGroupLogging")();var p=l(a);return(n==null?void 0:n.__typename)===null?null:k.jsx(c("TetraButton.react"),{icon:f?d("fbicon")._(i("505564"),16):d("fbicon")._(i("492450"),16),label:h._("__JHASH__jBb8zgdKj_r__JHASH__"),labelIsHidden:!0,onPress:function(){g(f),c("promiseDone")(m.load().then(function(a){a.log(function(){var a;return{attribution_id:(a=JSON.stringify(o==null?void 0:o.v2))!=null?a:"[]",current_surface:"group_mall",group_id:n==null?void 0:n.id,previous_surface:p.current,unit_name:"group_mall_recaffordance_caretbutton"}})}))},type:"secondary"})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("CometSearchEntityScope",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum")({GROUP:"group",PAGE:"page",USER:"user"});c=a;f["default"]=c}),66);
__d("XCometGroupScopedSearchControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/groups/{idorvanity}/search/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometPageScopedSearchControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/page/{idorvanity}/search/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometUserScopedSearchControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/profile/{idorvanity}/search/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("useCometEntityScopedSearchRouteUrlBuilder",["XCometGroupScopedSearchControllerRouteBuilder","XCometPageScopedSearchControllerRouteBuilder","XCometUserScopedSearchControllerRouteBuilder","react","useSearchCometResultsCommonRouteParamBuilder"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useCallback;function i(a){switch(a){case"group":return c("XCometGroupScopedSearchControllerRouteBuilder");case"page":return c("XCometPageScopedSearchControllerRouteBuilder");case"user":return c("XCometUserScopedSearchControllerRouteBuilder")}}function a(a){var b=a.entityID,d=a.entityType;a=babelHelpers.objectWithoutPropertiesLoose(a,["entityID","entityType"]);var e=c("useSearchCometResultsCommonRouteParamBuilder")(a);return h(function(a){return i(d).buildURL(babelHelpers["extends"]({idorvanity:b},e.build(a)))},[e,b,d])}g["default"]=a}),98);
__d("GroupsEntityScopedCometTypeaheadDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4958745114174592"}),null);