;/*FB_PKG_DELIM*/

__d("CometProfileAdCenterRootContentQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9500414703365048"}),null);
__d("CometProfileAdCenterRootContentQuery$Parameters",["CometProfileAdCenterRootContentQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometProfileAdCenterRootContentQuery_facebookRelayOperation"),metadata:{},name:"CometProfileAdCenterRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometUFIGroupCommentActorLink_actor.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometUFIGroupCommentActorLink_actor",selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},{kind:"InlineFragment",selections:[{alias:null,args:null,kind:"ScalarField",name:"url",storageKey:null}],type:"Entity",abstractKey:"__isEntity"}],type:"Actor",abstractKey:"__isActor"};e.exports=a}),null);
__d("CometUFIGroupCommentActorLink_groupCommentInfo$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"CometUFIGroupCommentActorLink_groupCommentInfo$normalization",selections:[{alias:null,args:null,concreteType:"Group",kind:"LinkedField",name:"group",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],storageKey:null},{alias:null,args:[{kind:"Variable",name:"feed_location",variableName:"feedLocation"},{kind:"Literal",name:"is_comet",value:!0}],kind:"ScalarField",name:"is_author_with_member_profile",storageKey:null}]};e.exports=a}),null);
__d("CometUFIGroupCommentActorLink_groupCommentInfo.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[{kind:"RootArgument",name:"feedLocation"}],kind:"Fragment",metadata:null,name:"CometUFIGroupCommentActorLink_groupCommentInfo",selections:[{alias:null,args:null,concreteType:"Group",kind:"LinkedField",name:"group",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],storageKey:null},{alias:null,args:[{kind:"Variable",name:"feed_location",variableName:"feedLocation"},{kind:"Literal",name:"is_comet",value:!0}],kind:"ScalarField",name:"is_author_with_member_profile",storageKey:null}],type:"GroupCommentInfo",abstractKey:null};e.exports=a}),null);
__d("cometUFIComposerGroupMentionsPlugin_plugin$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"cometUFIComposerGroupMentionsPlugin_plugin$normalization",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}]};e.exports=a}),null);
__d("cometUFIComposerGroupMentionsPlugin_plugin.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"cometUFIComposerGroupMentionsPlugin_plugin",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],type:"CommentComposerGroupMentionsPlugin",abstractKey:null};e.exports=a}),null);
__d("cometUFIComposerGroupMentionsPlugin_pluginData.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"InlineDataFragment",name:"cometUFIComposerGroupMentionsPlugin_pluginData"};e.exports=a}),null);
__d("GroupsCometMemberProfileLink.react",["ActorHovercard.react","CometHovercardGroupContext","CometLink.react","CometPressable.react","ProfileCometContextualProfileGating","XCometContextualProfileControllerRouteBuilder","mergeRefs","react","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i=d("react").useMemo;function a(a){var b=a.color,d=a.groupID,e=a.kind,f=e===void 0?"link":e;e=a.memberID;var g=a.xstyle,l=j(a),m=l.linkProps,n=l.ref;l=i(function(){return{groupID:d}},[d]);var o={"aria-hidden":a["aria-hidden"],"aria-label":a["aria-label"],children:a.children,focusable:a.focusable};return h.jsx("span",{className:c("stylex")(g),children:h.jsx(c("CometHovercardGroupContext").Provider,{value:l,children:h.jsx(c("ActorHovercard.react"),{actorID:e,"aria-hidden":a["aria-hidden"],display:"inline",children:function(a){a=c("mergeRefs")(a,n);switch(f){case"link":return h.jsx(c("CometLink.react"),babelHelpers["extends"]({},o,m,{color:b,ref:a}));case"profilePhoto":return h.jsx(c("CometPressable.react"),babelHelpers["extends"]({},o,k(m),{overlayRadius:"50%",ref:a}));default:return f}}})})})}a.displayName=a.name+" [from "+f.id+"]";function j(a){var b=a.groupID,e=a.hasMemberProfile,f=a.memberID,g=a.onClick;a=a.profileUrl;return d("ProfileCometContextualProfileGating").canViewCometContextualProfile()&&e?{linkProps:{href:c("XCometContextualProfileControllerRouteBuilder").buildURL({group_idorvanity:b,member_id:f}),onClick:g}}:{linkProps:{href:a,onClick:g}}}function k(a){var b=a.href,c=a.onClick;a=a.preventLocalNavigation;return{linkProps:{preventLocalNavigation:a,url:b},onPress:c}}g["default"]=a}),98);
__d("CometUFIGroupCommentActorLink.react",["CometRelay","CometUFIGroupCommentActorLink_actor.graphql","CometUFIGroupCommentActorLink_groupCommentInfo.graphql","GroupsCometMemberProfileLink.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=d("react");function a(a){var e=a.author,f=a.children,g=a.groupCommentInfo,k=a.kind;a=babelHelpers.objectWithoutPropertiesLoose(a,["author","children","groupCommentInfo","kind"]);e=d("CometRelay").useFragment(h!==void 0?h:h=b("CometUFIGroupCommentActorLink_actor.graphql"),e);g=d("CometRelay").useFragment(i!==void 0?i:i=b("CometUFIGroupCommentActorLink_groupCommentInfo.graphql"),g);var l=e.id,m=g.group;g=g.is_author_with_member_profile;m=m==null?void 0:m.id;return l==null||m==null?f:j.jsx(c("GroupsCometMemberProfileLink.react"),babelHelpers["extends"]({},a,{groupID:m,hasMemberProfile:(a=g)!=null?a:!1,kind:k,memberID:l,profileUrl:e==null?void 0:e.url,children:f}))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("CometUFIGroupMentionsComposerPluginInner.react",["react","useDeferredModuleOnReady"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a){var b=a.config,d=a.pluginProps;a=a.upgradedPluginDeferred_FOR_DRAFTJS_AND_OUTLINE;a=c("useDeferredModuleOnReady")(a);if(a==null)return null;else return h.jsx(a,{config:b,pluginProps:d})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("cometUFIComposerGroupMentionsPlugin",["CometRelay","CometUFIGroupMentionsComposerPluginInner.react","FBLogger","cometUFIComposerGroupMentionsPlugin_plugin.graphql","cometUFIComposerGroupMentionsPlugin_pluginData.graphql","requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=c("requireDeferred")("createUpgradedUFI2GroupMentionsComposerPluginForLexical").__setRef("cometUFIComposerGroupMentionsPlugin");h!==void 0?h:h=b("cometUFIComposerGroupMentionsPlugin_plugin.graphql");function a(a){a=a.fragmentKey;a=d("CometRelay").readInlineData(i!==void 0?i:i=b("cometUFIComposerGroupMentionsPlugin_pluginData.graphql"),a);var e=a.group_id;a=a.post_id;if(e==null||a==null)throw c("FBLogger")("ufight_club").mustfixThrow("This plugin cannot be rendered without group_id or post_id");e={groupID:e,postID:a,upgradedPluginDeferred_FOR_DRAFTJS_AND_OUTLINE:j};a=e.upgradedPluginDeferred_FOR_DRAFTJS_AND_OUTLINE;e=babelHelpers.objectWithoutPropertiesLoose(e,["upgradedPluginDeferred_FOR_DRAFTJS_AND_OUTLINE"]);return{above:null,action:null,below:c("CometUFIGroupMentionsComposerPluginInner.react"),id:"group_mentions",inside:null,props:{config:e,upgradedPluginDeferred_FOR_DRAFTJS_AND_OUTLINE:a}}}g["default"]=a}),98);
__d("CometVideoHomeFunnelLoggingContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext({hasPermalinkInjection:!1});g["default"]=b}),98);
__d("XCometFBReelControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/reel/{?video_id}/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("CometProfileAdCenterRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9139296982808746"}),null);